/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#2fd9f4",
        background: "#121317",
        outline: "#908fa0",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary-container": "#18294a",
        "inverse-on-surface": "#2f3035",
        "on-secondary": "#00363e",
        secondary: "#5de6ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface": "#e3e2e8",
        error: "#ffb4ab",
        "surface-container-low": "#1a1b20",
        primary: "#c0c1ff",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c0c1ff",
        "secondary-fixed": "#a2eeff",
        "on-primary-container": "#0d0096",
        "on-error": "#690005",
        "on-secondary-container": "#00515d",
        "on-surface-variant": "#c7c4d7",
        "surface-dim": "#121317",
        "outline-variant": "#464554",
        "surface-container": "#1f1f24",
        "on-primary": "#1000a9",
        "secondary-container": "#00cbe6",
        "inverse-primary": "#494bd6",
        "surface-container-highest": "#343439",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed-dim": "#b5c6f0",
        "on-background": "#e3e2e8",
        tertiary: "#b5c6f0",
        "on-tertiary-fixed-variant": "#364669",
        "error-container": "#93000a",
        "on-primary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#004e5a",
        "surface-container-high": "#292a2e",
        "primary-fixed": "#e1e0ff",
        "surface-variant": "#343439",
        "surface-bright": "#38393e",
        "on-tertiary": "#1f3052",
        "on-tertiary-fixed": "#071b3b",
        "inverse-surface": "#e3e2e8",
        surface: "#121317",
        "tertiary-container": "#8090b8",
        "on-secondary-fixed": "#001f25",
        "surface-container-lowest": "#0d0e12",
        "primary-container": "#8083ff",
        // Stellar brand accents
        "stellar-indigo": "#6366F1",
        "stellar-cyan": "#22D3EE",
        "stellar-deep": "#0B1E3F",
      },
      borderRadius: {
        DEFAULT: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Space Grotesk"', "sans-serif"],
        body: ["Inter", '"Space Grotesk"', "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
